### ISSUE TITLE
Favicon is filled with black

### ISSUE THREAD

**Issue by stevenlele** [dragonofmercy/Dragon-Better-History#10]
Running Edge 87.0.664.66 on Windows 10.

![](https://user-images.githubusercontent.com/15964380/103009946-79623680-4572-11eb-86e1-bdd45acaad07.png)

Apparently, Microsoft is filling their SVG icon with black in `edge://` urls, thus breaking this icon.

**Comment by dragonofmercy** [comment]
Hi, I close this issue, I know it's still persist but it's browser problem, I am in contact with Microsoft on this problem
