### ISSUE TITLE
[enhancement] 24-time format & Displaying Titles After The Hours

### ISSUE THREAD

**Issue by PureOcean** [dragonofmercy/Dragon-Better-History#14]
@dragonofmercy 

Thank you for this and "**Chrome Better History**" extension.

I manually installed this extension the Cent Browser. No problem but I miss some features of "Chrome Better History".

- No 24-hour format
- Titles are displays before the time.

Could you add these features, at least an option?

**Comment by dragonofmercy** [comment]
Hi, I have push the changes to Microsoft. It will take 2 or 3 day for review

**Comment by PureOcean** [comment]
I just tried it. Thank you very much for the **Options** feature (and [all new codes](https://github.com/dragonofmercy/Dragon-Better-History/commit/42a3d65cc5c6898cb8d01e0859a507332985dd53)).
