### ISSUE TITLE
Request: "Clear all in search result"

### ISSUE THREAD

**Issue by PureOcean** [dragonofmercy/Dragon-Better-History#17]
The **Chrome Better History** had the ability to batch delete all the records what containing the searched from the history. 
It was as follows:

> Search results for ..... [Clear all in search result]

Could you add this feature to Dragon Better History?
I guess, your code for this feature is [here](https://github.com/nickknissen/Chrome-Better-History/blame/629ddb001decc0dcb28b3fabb54786ad4799e125/assets/scripts.js#L226). 

But this is old version(3.2). [Chrome Better History's last version (3.50)](https://www.crx4chrome.com/crx/39058/) has different code. Excerpt from the Script.js:

>     $('#history-summary-clear').on('click', function(e){
>         e.preventDefault();
>         if(confirm(chrome.i18n.getMessage('search_clear_confirm'))){
>             $('.remove-single').each(function(){
>                 $(this).click();
>             });
>         }
>     })

**Comment by dragonofmercy** [comment]
Search something, unfocus the search input (click somewhere in the page) then press CTRL+A and click on delete button on the top just like Edge default history

**Comment by PureOcean** [comment]
> Search something, unfocus the search input (click somewhere in the page) then press CTRL+A and click on delete button on the top just like Edge default history

I didn't know this native the feature. Thank you for explain.
