### ISSUE TITLE
Request: Add "Recently closed" tab to the extension's pop-up

### ISSUE THREAD

**Issue by BarnMTB** [dragonofmercy/Dragon-Better-History#25]
Since the extension currently not only replaces Edge's History page but also the floating History pop-up, it would be a good idea to add a "Recently closed" section that shows recently closed tabs and windows like Edge's do.

_Photo of the current floating History pop-up:_
![image](https://user-images.githubusercontent.com/16902530/155211756-3ecc46db-177f-42e8-b6f9-f432789155b3.png)

I often used the "Recently closed" section to reopen tabs and windows that I previously closed. The lack of this functionality while also being blocked access to it while the extension is enabled is a bit cumbersome. and I find using CTRL+Shift+T less intuitive.

(I completely understand why it's not possible to add "Tabs from other devices" since that is related to Microsoft Account and their data propriety data sync.)

**Comment by dragonofmercy** [comment]
Available with the version 2.1.0
