### ISSUE TITLE
Why does it no longer support chrome?

### ISSUE THREAD

**Issue by mingyEx** [dragonofmercy/Dragon-Better-History#27]
I can't find this plugin in the chrome extension store.

**Comment by dragonofmercy** [comment]
This extension have been made for Microsoft Edge, I don't want to update it for Chrome, because I don't use Chrome anymore.

**Comment by raingart** [comment]
https://github.com/dragonofmercy/Dragon-Better-History/issues/29#issuecomment-1642174968

**Comment by dragonofmercy** [comment]
Back on Chrome -> https://chromewebstore.google.com/detail/dragon-better-history/eagfijenmngbjkbmfaogdknnididhaoa
