### ISSUE TITLE
Some icons cannot be displayed in recent days

### ISSUE THREAD

**Issue by bling-yshs** [dragonofmercy/Dragon-Better-History#28]
### Steps to reproduce

![001](https://user-images.githubusercontent.com/41812674/191530267-995b066b-853a-47cc-b9aa-beebc9de25a0.png)

### ✔️ Expected Behavior

Icons display normally

### ❌ Actual Behavior

Some icons disappear

### Microsoft Edge Version

105.0.1343.42

**Comment by bling-yshs** [comment]
This problem also exists on my server, so I'm sure it's not an isolated case.
![002](https://user-images.githubusercontent.com/41812674/191532296-37a5558e-12b4-4844-b8db-b6869d5e4831.png)

**Comment by dragonofmercy** [comment]
OK I see the problem too, it's only with the light theme, I don't know why the browser get the default icon for the dark theme, I will try to fix that

**Comment by dragonofmercy** [comment]
Published to the store waiting for review, can take 3 to 7 days
