### ISSUE TITLE
This is a perfect crx and I love it so much

### ISSUE THREAD

**Issue by f59375543** [dragonofmercy/Dragon-Better-History#29]
But please, why was it removed from the Chrome store？

**Comment by raingart** [comment]
Hi all!
i published the extension in webstore
https://chrome.google.com/webstore/detail/pmolchcgkagchldkgphmlaplgmagldfn/

I hope the author will not mind

**Comment by dragonofmercy** [comment]
You can publish a fork of this version but you need to change the name and all link pointing to this repo.  
I don't want to process support requests for Chrome !

**Comment by raingart** [comment]
If moderation passes, then I will change it.
Thank you for creating it
