### ISSUE TITLE
Does this addon keep History after being wiped by Edge?

### ISSUE THREAD

**Issue by dundundunnn** [dragonofmercy/Dragon-Better-History#31]
Edge wipes the history after 90 days, does this addon able to maintain the history even after it is wiped? If not can I request a feature to maintain the history in a backup

**Comment by dragonofmercy** [comment]
> does this addon able to maintain the history even after it is wiped?  

Nope because the brower api cannot handle this.

> If not can I request a feature to maintain the history in a backup

I will not implement this functionality, for security reasons.  
This plugin only use information from the browser api.
