### ISSUE TITLE
Cannot open "file:///" history

### ISSUE THREAD

**Issue by ChestnutA** [dragonofmercy/Dragon-Better-History#32]
### Steps to reproduce

I am not able to open the history web using file protocol. When I use Edge as a pdf viewer, this feature brings a little inconvenience.

Furthermore, I hope there will be a button to toggle the bold font.

### ✔️ Expected Behavior

- Be able to open pdf file history.
- Be able to control the font is bold or not.

### Microsoft Edge Version

131.0.2903.51

**Comment by dragonofmercy** [comment]
Hi, the new version has been submitted to Microsoft, waiting for approval

**Comment by dragonofmercy** [comment]
The update is available, don't forget to check "Allow access to file URL" in extention details

![image](https://github.com/user-attachments/assets/9a4f7636-f319-40ee-9bbd-56d2baa2d9c8)

**Comment by ChestnutA** [comment]
Thank you so much!






发件人：Dragon ***@***.***>
发送日期：2024-12-03 14:48:25
收件人：dragonofmercy/Dragon-Better-History ***@***.***>
抄送人：ChestnutA ***@***.***>,Author ***@***.***>
主题：Re: [dragonofmercy/Dragon-Better-History] Cannot open "file:///" history (Issue #32)

The update is available, don't forget to check "Allow access to file URL" in extention details
image.png (view on web)
