### ISSUE TITLE
Will chrome version of better-history continue to be maintained?

### ISSUE THREAD

**Issue by tjx666** [dragonofmercy/Dragon-Better-History#6]

**Comment by dragonofmercy** [comment]
Nope, the chrome extension was deleted, I suggest you to use this one  
https://chrome.google.com/webstore/detail/recent-history/fbmkfdfomhhlonpbnpiibloacemdhjjm

**Comment by VetaLioSTV** [comment]
@dragonofmercy what happened, why you have deleted extension from store ?
