### ISSUE TITLE
Can't open the history page by hot key

### ISSUE THREAD

**Issue by Hermine2** [dragonofmercy/Dragon-Better-History#7]
I recently found that the history viewing page can't be open by "Ctrl + H" but it works when I click the icon of the extension. Idk if this is your idea but it is very inconvenient. Would you help me to fix this? I'lll appreciate it!
I am using Microsoft Edge Version 88.0.685.3 (Official build) dev (64-bit) and I've updated to the latest version of the extension.

**Comment by justin-hackin** [comment]
I had this problem initially but after I opened the window via the extension icon the shortcuts started to work

**Comment by dragonofmercy** [comment]
Fixed with commit 48eb61b8136126a3950801a1e289dc0272542cc3, waiting for Microsoft validation
