### ISSUE TITLE
Ctrl+H Opens popup, extensions isn't viewed properly

### ISSUE THREAD

**Issue by ynavott** [dragonofmercy/Dragon-Better-History#8]
When I click the extension icon the last 10 items show up properly, and I am able to click "View Full History" to see the extension in a full page. But, when I click Ctrl+H it opens up a popup that doesn't show the extension correctly. A screenshot is attached.

![EdgeHistory](https://user-images.githubusercontent.com/48953594/101755713-dfb07900-3add-11eb-8c0f-ca246cf291b1.png)

As you can see, it only shows the calendar portion and the scrollbars, and while the scrollbars are functional (you can see a sliver of the actual text moving up and down on the right side) it is impossible to view the extension properly.

**Comment by dragonofmercy** [comment]
It's very strange, I need to investigate a little bit, the good news is that I have the problem too, but I don't know why it's doing this.

**Comment by dragonofmercy** [comment]
Ok I find something, Edge have changed the display of the history when you click on History or use CTRL+H shortcut, from know I don't know how to override this, nothing is mentioned in Microsoft documentation site now.
